<?php 
$store = Mage::app()->getStore();
$_helper = $this->helper('catalog/output');
$code  = $store->getCode();
?>
<?php if($this->getItems()->getSize()): ?>
<div class="home-products-grid-container category-products">
    <ul class="products-grid column<?php echo $this->get_product_column() ?> row">
        <?php foreach($this->getItems() as $_item): ?>
            <li class="item">
                    <div class="item-area">
                        <div class="product-image-wrapper <?php if (Mage::getStoreConfig('legenda_setting/category/effect_img', $code)): ?>hover-effect-slider"<?php endif; ?>>
                        <?php 
                            // Get the Special Price
                            $specialprice = Mage::getModel('catalog/product')->load($_item->getId())->getSpecialPrice(); 
                            // Get the Special Price FROM date
                            $specialPriceFromDate = Mage::getModel('catalog/product')->load($_item->getId())->getSpecialFromDate();
                            // Get the Special Price TO date
                            $specialPriceToDate = Mage::getModel('catalog/product')->load($_item->getId())->getSpecialToDate();
                            // Get Current date
                            $today =  time();
                         
                            if ($specialprice){
                                if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)){
                                    if(Mage::getStoreConfig("legenda_setting/product_label/sale", $code)){
                        ?>
                                    <span class="label-icon sale-label">Sale!</span>
                        <?php       
                                    }
                                }
                            }
                        ?>
                        <?php
                            $now = date("Y-m-d");
                            $newsFrom= substr($_item->getData('news_from_date'),0,10);
                            $newsTo=  substr($_item->getData('news_to_date'),0,10);
                            if ($newsTo != '' || $newsFrom != ''){
                                if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo))
                                {
                                    if(Mage::getStoreConfig("legenda_setting/product_label/new", $code)){
                            ?> 
                                    <span class="label-icon new-label second-label">New!</span>
                            <?php 
                                    }
                                }
                            }
                        ?>
                        <?php 
                            $imgList = ''; 
                            if (Mage::getStoreConfig('legenda_setting/category/effect_img', $code)) {
                                $product = Mage::getModel('catalog/product')->load($_item->getId());
                                foreach ($product->getMediaGalleryImages() as $image) {
                                    // If no image, skip 
                                    if ($image->getFile() == NULL)
                                        continue;
                                    if (Mage::getStoreConfig('legenda_setting/category/aspect_ratio', $code)) {
        //                                $imgList .= Mage::helper('catalog/image')->init($_item, 'thumbnail', $image->getFile()).',';
                                        $imgList .= Mage::helper('catalog/image')->init($_item,'thumbnail',$image->getFile())->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(350).',';   
                                    } else {
                                        $imgWidth = Mage::getStoreConfig('legenda_setting/category/ratio_width', $code);
                                        $imgHeight = Mage::getStoreConfig('legenda_setting/category/ratio_height', $code);
                                        $imgList .= Mage::helper('catalog/image')->init($_item,'thumbnail',$image->getFile())->resize($imgWidth, $imgHeight).',';
                                    }
                                }
                                $imgList = substr($imgList, 0, strlen($imgList) - 1);
                            }
                        ?>
                        <?php if(!$_item->isSaleable()): ?>
                            <span class="out-of-stock"><?php echo $this->__('Out of stock') ?></span>
                        <?php endif; ?>
                        <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_item, 'small_image'), null, true) ?>" class="product-image" data-images-list="<?php echo $imgList; ?>">
                            <img src="<?php if(Mage::getStoreConfig('legenda_setting/category/aspect_ratio', $code)):?><?php echo $this->helper('catalog/image')->init($_item, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(350); ?><?php else: ?><?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(Mage::getStoreConfig('legenda_setting/category/ratio_width', $code), Mage::getStoreConfig('legenda_setting/category/ratio_height', $code)); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_item, 'small_image'), null, true) ?>" />
                        </a>
                        <?php if (Mage::getStoreConfig('quickview/general/enableview', $code)): ?>
						    <a href="<?php echo $_item->getId() ?>" class="sw-product-quickview"><?php echo $this->__('Quick View') ?></a>
                        <?php endif; ?>
                        </div>
                        <div class="description-wrapper">
                            <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_item, $_item->getName(), 'name') ?></a></h3>
                            <?php if($_item->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_item, 'short') ?>
                            <?php endif; ?>
                            <?php echo $this->getPriceHtml($_item, true) ?>
                            <div class="actions">
                            <?php if(Mage::getStoreConfig('ajaxcart/addtocart/enablecategory')): ?>
                                <?php if($_item->isSaleable()): ?>
                                    <?php  if ( !($_item->getData('has_options') || $_item->isGrouped()) ) :  ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart btn-cart-<?php echo $_item->getId()?>" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_item) ?>','<?php echo $_item->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                    <?php else: ?>
                                        <button type="button" title="<?php echo $this->__('Select Option') ?>" class="button btn-cart btn-cart-<?php echo $_item->getId()?>" onclick="showOptions('<?php echo $_item->getId()?>')"><span><span><?php echo $this->__('Select Option') ?></span></span></button>
                                        <a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_item->getId()));?>' class='fancybox' id='fancybox<?php echo $_item->getId()?>' style='display:none'>Options</a>
                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php else: ?>
                                <?php if($_item->isSaleable()): ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php endif; ?>
                            <?php endif; ?>
                            
                            <?php if(Mage::getStoreConfig('ajaxcart/addtolinks/enablecategory')): ?>
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="#" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_item) ?>","<?php echo $_item->getId()?>");return false;' class="link-wishlist link-wishlist-<?php echo $_item->getId()?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
                                        <li><span class="separator">|</span> <a href="#" onclick='ajaxCompare("<?php echo $_compareUrl ?>","<?php echo $_item->getId()?>");return false;' class="link-compare link-compare-<?php echo $_item->getId()?>"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>                        
                                </ul>
                            <?php else: ?>
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_item) ?>" class="link-wishlist button"></a></li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
                                        <li><a href="<?php echo $_compareUrl ?>" class="link-compare button"></a></li>
                                    <?php endif; ?>
                                </ul>
                            <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </li>
        <?php endforeach; ?>  
    </ul>
    <script type="text/javascript">
        jQuery('.col-main .products-grid li:nth-child(2n)').addClass('nth-child-2n');
        jQuery('.col-main .products-grid li:nth-child(2n+1)').addClass('nth-child-2np1');
        jQuery('.col-main .products-grid li:nth-child(3n)').addClass('nth-child-3n');
        jQuery('.col-main .products-grid li:nth-child(3n+1)').addClass('nth-child-3np1');
        jQuery('.col-main .products-grid li:nth-child(4n)').addClass('nth-child-4n');
        jQuery('.col-main .products-grid li:nth-child(4n+1)').addClass('nth-child-4np1');
        jQuery('.col-main .products-grid li:nth-child(5n)').addClass('nth-child-5n');
        jQuery('.col-main .products-grid li:nth-child(5n+1)').addClass('nth-child-5np1');
    </script>
</div>
<?php else: ?>
<div class="content-element">
	<div class="note-msg"><span class="msg-content"><?php echo $this->__('There are no products matching the selection.') ?></span></div>
</div>
<?php endif; ?>