<?php 
$logged		= $this->isCustomerLoggedIn();
$has_addr	= $this->customerHasAddresses();
?>
<div class="onepagecheckout_block">
    <h3>
		<?php	echo $this->__('Name & Address');	?>
    </h3>
    <ul class="form-list">
    <?php if ($has_addr){ ?>
        <li class="fields">
            <div class="full">
                <label for="billing_cutomer_address">
            	    <?php echo $this->__('Select a billing address from your address book or enter a new address.') ?>
                </label>
                <div class="input-box">
                    <?php echo $this->getCustomerBillAddr() ?>
                </div>
            </div>
        </li>
    <?php } ?>
	    <li id="bill_form"<?php if ($has_addr) {echo ' style="display:none;" ';} ?>>
            <fieldset>
			<input type="hidden" name="billing[address_id]" id="billing:address_id" value="<?php echo $this->getBillAddress()->getId() ?>" />
            <ul>
			    <li class="fields">
				    <?php echo $this->getLayout()->createBlock('onepagecheckout/widget_name')->setObject($this->getBillAddress())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
			    </li>
			    <?php if (!$logged)  : ?>
				<li class="fields">
                    <div class="field">
					    <label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
					    <div class="input-box">
						    <input type="text" name="billing[email]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" placeholder="<?php echo $this->__('your@domain.com')?>"/>
					    </div>
				    </div>
                </li> 
			<?php endif;
			 
			$cr = Mage::getStoreConfig('onepagecheckout/address_form/company');
			if ($cr !== 'hidden') : ?>
			<li class="fields">
                <div class="full">
				    <label for="billing:company" <?php if ( $cr  === 'required' ){ echo 'class="required"'; }?> ><?php if ($cr  === 'required'){echo "<em>*</em>";}?> <?php echo $this->__('Company') ?> </label>
				    <div class="input-box">
				        <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text<?php if($cr === 'required'){ echo ' required-entry';} ?>" placeholder="<?php echo $this->__('Company')?>"/>
				    </div>
                </div>
			</li>    
			<?php endif; 
            
			$ar	= Mage::getStoreConfig('onepagecheckout/address_form/address');
			if ($ar !== 'hidden') : 
			?>
	        <li class="fields">
                <div class="full">
				    <label for="billing:street1"<?php if($ar === 'required'){echo ' class="required" ';}?> ><?php if($ar === 'required'){echo '<em>*</em>';}?> <?php echo $this->__('Address') ?> </label>
				    <div class="input-box">
				        <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getBillAddress()->getStreet(1)) ?>" class="input-text<?php if($ar === 'required'){echo ' required-entry';}?>" placeholder="<?php echo $this->__('Street address') ?>"/>
				    </div>
                </div>
			</li>
			<?php 
			$csl	= $this->helper('customer/address')->getStreetLines();
			for ($i = 2; $i <= $csl; $i++){ 
			?>
			<li class="fields">
                <div class="full">
			        <div class="input-box">
				        <input type="text" name="billing[street][]" id="billing:street<?php echo $i?>" title="<?php echo $this->__('Street Address %s', $i) ?>" value="<?php echo $this->htmlEscape($this->getBillAddress()->getStreet($i)) ?>" class="input-text" placeholder="<?php echo $this->__('Apartment, suite, unit etc. (optoinal)') ?>"/>
				    </div>
                </div>
			</li>
			<?php 
			}
				
			endif;

			$city_r = Mage::getStoreConfig('onepagecheckout/address_form/city');
			$state_r= Mage::getStoreConfig('onepagecheckout/address_form/state');
			?>
			<li class="fields"<?php if(($city_r === 'hidden' && $state_r === 'hidden')){echo ' style="display:none"';}?> >
			<?php if ($city_r !== 'hidden') : ?>
				<div class="field">
				<label for="billing:city"<?php if ($city_r === 'required'){ echo ' class="required" ';}?>>
						<?php if ($city_r === 'required'){ echo ' <em>*</em> ';}?><?php echo $this->__('City') ?>
				</label>
					
				<div class="input-box">
					<input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getCity()) ?>" class="input-text<?php if ($city_r === 'required'){ echo ' required-entry ';}?>" id="billing:city" placeholder="<?php echo $this->__('City')?>"/>
				</div>
			</div>
		    <?php endif; ?>
				<div class="field"<?php if($state_r === 'hidden'){ echo ' style="display:none" ';}?>>
					<label for="billing:region_id"<?php if($state_r === 'required'){ echo ' class="required" ';}?>>
						    <?php if($state_r === 'required'){ echo ' <em>*</em> ';}?><?php echo $this->__('State / Province') ?>
					</label>
					    
					<div class="input-box">
						<select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select<?php if($state_r === 'required') { echo ' required-entry';}?>" style="display:none;">
							<option value=""><?php echo $this->__('Select One') ?></option>
						</select>
						<script type="text/javascript">
						//<![CDATA[
							$('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getBillAddress()->getRegionId() ?>");
						//]]>
						</script>
						    <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getRegion()) ?>"  title="<?php echo $this->__('State / Province') ?>" class="input-text<?php if($state_r === 'required'){ echo ' required-entry';}?>" style="display:none;" placeholder="<?php echo $this->__('State / Province') ?>"/>
					</div>
				</div>
			</li>
			<?php
			$zip_r	= Mage::getStoreConfig('onepagecheckout/address_form/zip');
			$phone_r= Mage::getStoreConfig('onepagecheckout/address_form/phone');
			if ($zip_r !== 'hidden' || $phone_r !== 'hidden') : 
			?>
			<li class="fields">                
			<?php if ($zip_r !== 'hidden') : ?>
				<div class="field">
					<label for="billing:postcode"<?php if($zip_r === 'required'){echo ' class="required" ';}?>>
							<?php if($zip_r === 'required'){echo ' <em>*</em>';}?><?php echo $this->__('Zip Code') ?>
					</label>
						
					<div class="input-box">
							<input type="text" title="<?php echo $this->__('Zip Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getBillAddress()->getPostcode()) ?>" class="input-text validate-zip-international<?php if($zip_r === 'required'){echo ' required-entry ';}?>" placeholder="<?php echo $this->__('Postcode / Zip') ?>"/>
					</div>
				</div>
			<?php endif; ?>
			<?php if ($phone_r !== 'hidden') : ?>
				<div class="field">
					<label for="billing:telephone"<?php if($phone_r === 'required') { echo ' class="required" ';}?>>
							<?php if($phone_r === 'required') { echo ' <em>*</em> ';}?><?php echo $this->__('Telephone') ?>
					</label>
						
					<div class="input-box">
						<input type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text<?php if($phone_r === 'required') { echo ' required-entry ';}?>" id="billing:telephone" placeholder="<?php echo $this->__('Telephone')?>"/>
					</div>
				</div>
			<?php endif; ?>
			</li>
			<?php endif ?>
	        
	        <?php
	        $country_r = Mage::getStoreConfig('onepagecheckout/address_form/country');  
	        ?>        
			<li class="fields"<?php if($country_r === 'hidden'){ echo ' style="display:none" ';}?>>
                <div class="field">
				    <label for="billing:country_id"<?php if($country_r === 'required') { echo ' class="required" ';}?>>
	        		        <?php if($country_r === 'required') { echo ' <em>*</em> ';}?> <?php echo $this->__('Country') ?>
	        	    </label>
	        	        
				    <div class="input-box">
					    <?php echo $this->getBillingCountriesSelectBox() ?>
				    </div>
                </div>
			</li>
	
			<?php
			$fax_r	= Mage::getStoreConfig('onepagecheckout/address_form/fax');
			if ($fax_r !== 'hidden') : 
			?>
			<li class="fields">
				<div class="field">
					<label for="billing:fax"<?php if($fax_r === 'required') {echo ' class="required" ';}?>>
						    <?php if($fax_r === 'required') {echo ' <em>*</em> ';}?><?php echo $this->__('Fax') ?>
					</label>
					    
					<div class="input-box">
						<input type="text" name="billing[fax]" value="<?php echo $this->htmlEscape($this->getBillAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text<?php if($fax_r === 'required') {echo ' required-entry ';}?>" id="billing:fax" placeholder="<?php echo $this->__('Fax')?>"/>
					</div>
				</div>
			</li>
			<?php 
			endif; 
	 
			if (!$logged) :
			
				$dob	= $this->getLayout()->createBlock('onepagecheckout/widget_dob');
				$gender	= $this->getLayout()->createBlock('onepagecheckout/widget_gender');
				$taxvat = $this->getLayout()->createBlock('onepagecheckout/widget_taxvat');

				if ($dob->isEnabled() || $gender->isEnabled()){ ?>
					    <li class="fields">
						<?php if ($dob->isEnabled()):	?>
						<div class="field">
							<?php 
								echo $dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml(); 
							?>
						</div>
						<?php endif; ?>
						<?php if ($gender->isEnabled()):	?>
						<div class="field">
							<?php 
								echo $gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml();
							?>
						</div>
						<?php endif ?>
					</li>
				<?php 
				} 

				if ($taxvat->isEnabled()){	?>
					    <li class='fields'>
						<?php 
							echo $taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml(); 
						?>
					</li>
				<?php 
				}
				$agc = Mage::helper('onepagecheckout')->isGuestCheckoutAllowed();
				if ($agc) 
				{
				?>
					<li class="control">
						<input type="checkbox" name="billing[register_account]" value="1" title="<?php echo $this->__('Create an account for later use') ?>" id="billing:register_account" onclick="if(window.billing) billing.setCreateAccount(this.checked);"<?php if ($this->getBillAddress()->getRegisterAccount()):?> checked="checked"<?php endif;?> class="checkbox" />
						<label for="billing:register_account">
							<?php echo $this->__('Create an account for later use') ?>
						</label>
					</li>
				<?php
				} 
				else
				{ 				
				?>
                    <li class="control">
					<input type="hidden" name="billing[register_account]" value="1"/>
                                       </li>
				<?php 
				} 
				?>
				<li class="fields" id="register-customer-password" <?php if ($agc) { echo ' style="display: none;" '; } ?>>
					<div class="field">
						    <label for="billing:customer_password" class="required"><em>*</em>
							<?php echo $this->__('Password') ?>
						</label>
						    
						<div class="input-box">
							<input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" placeholder="<?php echo $this->__('Password')?>"/>
						</div>
					</div>
					<div class="field">
						    <label for="billing:confirm_password" class="required"><em>*</em>
							<?php echo $this->__('Confirm Password') ?>
						</label>
						<div class="input-box">
							<input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" placeholder="<?php echo $this->__('Confirm Password') ?>"/>
						</div>
					</div>
				</li>
			<?php 
			endif; 
			?>
			<?php 
			if ($logged && $has_addr){
			?>
				    <li class="control">
					<input type="checkbox" class="checkbox" name="billing[save_in_address_book]" id="billing:save_in_address_book" value="1" title="<?php echo $this->__('Save in address book') ?>" <?php if ($this->getBillAddress()->getSaveInAddressBook()){ echo ' checked="checked" ';}?> />
					<label>
						<?php echo $this->__('Save in address book'); ?>
					</label>
				</li>
			<?php 
			}
			else
			{
			?>
				<li class="no-display">
					<input type="hidden" value="1" name="billing[save_in_address_book]" />
				</li>
			<?php 
			} 
			?>
			</ul>
            </fieldset>
	    </li>
    
    <?php 
    if (Mage::helper('onepagecheckout')->isShippingAddressAllowed() && $this->canShip()){ 
    ?>
    <li>
    	<input type="hidden" name="billing[use_for_shipping]" id="billing:use_for_shipping" value="<?php echo ($this->isUseBillingAddressForShipping())?'1':'0'; ?>" />
    </li>
    <?php 
    }else{ 
    ?>
    <li>
    	<input type="hidden" name="billing[use_for_shipping]" value="1" />
    </li>
    <?php 
    } 
    ?>
	</ul>
</div>

<script type="text/javascript">
//<![CDATA[
	var billing = new BillingAddress();
	RegionUpdater.prototype.setMarkDisplay = function(){};
	ZipUpdater.prototype._setPostcodeOptional = function(){};
	var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');
//]]>
</script>