<div class="page-title">
    <h1 class='h1_opc'><?php echo Mage::getStoreConfig('onepagecheckout/general/title') ?></h1>
    Fill in the fields below to complete your purchase!    
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="row">
    <div class="col-md-6">
        <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){ ?>
        <p class="onepagecheckout_loginarea">
            <?php echo $this->__('Already registered?') ?>
            <a href="javascript:void(0)" class="onepagecheckout_loginlink" onclick='open_login();'>
                <?php echo $this->__('Click here to login') ?>
            </a>
        </p>
        <div class="opc-customer-container">
        <?php 
            echo $this->getChildHtml('customer.login');
            echo $this->getChildHtml('customer.forgot');
        ?>
        </div>
        <?php 
        }    
        ?>
      
    </div>
</div>
<?php
$seq_http	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
  
?>
<script type="text/javascript">
	var http_type	= '<?php if($seq_http){echo 'https';}else{echo 'http';}?>';
</script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('onepagecheckout/js/onepagecheckout.js') ?>"></script>

<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>

<form action="" id="onepagecheckout_orderform">
<?php //updated from version 1.2.0 ?>  
<p>
	<?php echo $this->__('Have a coupon?') ?>
	<a href="javascript:void(0)" class="onepagecheckout_couponlink" onclick='open_coupon();'>
		<?php echo $this->__('Click here to enter your code') ?>
	</a>
</p>
<div id="checkout-coupon-discount-load">        
	<?php echo $this->getChildHtml('coupon') ?>
</div>
<div class="onepagecheckout_datafields row">
    <div class="col-md-6">
        <?php echo $this->getChildHtml('billing.address') ?>
        <hr>
        <?php echo $this->getChildHtml('shipping.address') ?>
        <hr>
        <?php echo $this->getChildHtml('shipping.method') ?>
        <hr>
        <?php echo $this->getChildHtml('payment.method') ?>                 
        <?php if (Mage::getStoreConfig('onepagecheckout/general/comment')) : ?>
        <hr>
        <div class="op_block_title">
            <?php echo $this->helper('sales')->__('Comment') ?>
        </div>        
        <ul class="form-list">
            <li class="fields">
                <div class="input-box" id='comment-block'>
                    <textarea name="order-comment" id="order-comment"><?php echo trim(Mage::getSingleton('customer/session')->getOrderCustomerComment()) ?></textarea>
                </div>
            </li>
        </ul>
        <?php endif; ?>
        <?php if (Mage::helper('onepagecheckout')->isSubscribeNewAllowed()) : ?>
        <hr>
        <p class="newsletter">
            <input type="checkbox" id="newsletter-signup" name="newsletter" value="1" title="<?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>" class="checkbox" />
            <label for="newsletter-signup">
                <?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>
            </label>
        </p>
        <?php endif; ?>
    </div>

    <div class="col-md-6">
        <?php echo $this->getChildHtml('review') ?>
    </div>
</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var checkout = new OPC('onepagecheckout_orderform', {
    	save    : '<?php echo $this->getUrl('onepagecheckout/index/saveOrder', array('_secure'=>$seq_http)) ?>',
    	update  : '<?php echo $this->getUrl('onepagecheckout/index/updateCheckout', array('_secure'=>$seq_http)) ?>',
        success : '<?php echo $this->getUrl('onepagecheckout/index/success', array('_secure'=>$seq_http)) ?>',
        failure : '<?php echo $this->getUrl('checkout/cart') ?>'
    }, "<?php echo $this->__('Please agree to all the terms and conditions.') ?>");

    document.observe("dom:loaded", function() {
        var win_triggers	= Array();
   		$$('.checkout-agreements .agree a').each(function(item){
   			var obj	= {
   				el: $$('.' + item.className),
   		   		event: 'click',
				window: $(item.className + '-window')
			};
   			win_triggers.push(obj);
        });
		opc_window	= new OPC.Window({triggers: win_triggers});
    });
//]]>
</script>