<?php $_categories = $this->getCurrentChildCategories(); ?>
<?php $_count = is_array($_categories)?count($_categories):$_categories->count(); ?>
<?php if ($_count): ?>
<div class="sidebar-item">
<h4 class="widget-title"><?php echo $this->__('Sub Categories') ?></h4>
    <ul class="product-categories ">
        <?php foreach($_categories as $_category): ?>
            <?php $children = explode(",", $_category->getChildren()); ?>
            <?php 
            $itemClass = ''; 
            if ($this->isCategoryActive($_category)) {
                $itemClass = 'current-cat';
            }
            if ($children[0]) {
                $itemClass .= ' cat-parent';
            }
            ?>
            <li class="cat-item <?php echo $itemClass ?>">
                <a href="<?php echo $this->getCategoryUrl($_category)?>">
                    <?php echo $this->htmlEscape($_category->getName()) ?>
                </a>
                <?php if ($children[0]) : ?>
                    <ul class="children">
                    <?php foreach($children as $child): ?>
                        <?php $_subcat = Mage::getModel('catalog/category')->load($child); ?>
                        <li class="cat-item">
                            <a href="<?php echo $this->getCategoryUrl($_subcat)?>">
                                <?php echo $this->htmlEscape($_subcat->getName()) ?>
                            </a> 
                        </li>
                    <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>